### ISSUE TITLE
overflow when using mobile

### ISSUE THREAD

**Issue by yurigo** [midudev/midu.link#1]
Al visitar [`midu.link`](midu.link) con un dispositivo movil el `body` tiene un desbordamiento.

![imagen](https://github.com/midudev/midu.link/assets/5684699/44112c95-d31f-4ead-aa0a-08e2d549fed5)

**Comment by yurigo** [comment]
Esta issue se produce cuando los textbox `hash to use for the link` y `auth code` están en la misma columna y el ancho de la pantalla es muy estrecha.  Para solucionarlo se añadieron las siguientes reglas css:

```css
    div {
      display: flex;
      }
      
    @media (width < 400px) {
      div {
        flex-direction: column;
      }
    }
```

Cuando el ancho de la pantalla sea inferior a 400px los dos textbox se pondrán uno debajo del otro (solucionando el overflow).

**Problema**: El ancho de `400px `no es del todo preciso: iPhone 11 Pro Max y iPhone Xs Max tienen un ancho de `414px`, iPhone 13 Pro Max y iPhone 12 Pro Max tienen un ancho de `428px`, iPhone 14 Pro Max tienen un ancho de `430px`.

**Solución**: Recomiendo utilizar `width <= 430px`
